### ISSUE TITLE
[BUG] plugin install fails due to a missing file - plugin-descriptor.properties in the generated zip  

### ISSUE THREAD

**Issue by rakeshgl** [opensearch-project/opensearch-oci-object-storage#10]
### What is the bug?
_A clear and concise description of the bug._
plugin installation fails due to a missing file - plugin-descriptor.properties in the generated zip  

### How can one reproduce the bug?
_Steps to reproduce the behavior._
1) Build the plugin by running - "mvn clean install -PAdvanced" as per the instructions in https://github.com/opensearch-project/opensearch-oci-object-storage .
2) Try to install the plugin with - ${OPENSEARCH_HOME}/bin/opensearch-plugin install file://target/releases/oci_repository_plugin-1.2.4.zip .
This fails with - 

 => ERROR [builder 20/20] RUN /usr/share/opensearch/bin/opensearch-plugin install file:///opensearch/build/distributions/oci-repo  1.8s
------
 > [builder 20/20] RUN /usr/share/opensearch/bin/opensearch-plugin install file:///opensearch/build/distributions/oci-repository-plugin-1.2.4.zip:
#33 1.409 -> Installing file:///opensearch/build/distributions/oci-repository-plugin-1.2.4.zip
#33 1.410 -> Downloading file:///opensearch/build/distributions/oci-repository-plugin-1.2.4.zip
[=================================================] 100%?? 
#33 1.767 -> Failed installing file:///opensearch/build/distributions/oci-repository-plugin-1.2.4.zip
#33 1.767 -> Rolling back file:///opensearch/build/distributions/oci-repository-plugin-1.2.4.zip
#33 1.776 -> Rolled back file:///opensearch/build/distributions/oci-repository-plugin-1.2.4.zip
#33 1.776 Exception in thread "main" java.nio.file.NoSuchFileException: /usr/share/opensearch/plugins/.installing-3440767207327395062/plugin-descriptor.properties
#33 1.777 	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
#33 1.777 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
#33 1.777 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
#33 1.777 	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
#33 1.778 	at java.base/java.nio.file.Files.newByteChannel(Files.java:370)
#33 1.778 	at java.base/java.nio.file.Files.newByteChannel(Files.java:421)
#33 1.778 	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
#33 1.778 	at java.base/java.nio.file.Files.newInputStream(Files.java:155)
#33 1.779 	at org.opensearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:229)
#33 1.779 	at org.opensearch.plugins.InstallPluginCommand.loadPluginInfo(InstallPluginCommand.java:799)
#33 1.779 	at org.opensearch.plugins.InstallPluginCommand.installPlugin(InstallPluginCommand.java:858)
#33 1.779 	at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:263)
#33 1.779 	at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:237)
#33 1.780 	at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:100)
#33 1.780 	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
#33 1.780 	at org.opensearch.cli.MultiCommand.execute(MultiCommand.java:104)
#33 1.780 	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
#33 1.780 	at org.opensearch.cli.Command.main(Command.java:101)
#33 1.780 	at org.opensearch.plugins.PluginCli.main(PluginCli.java:60)
------
executor failed running [/bin/sh -c /usr/share/opensearch/bin/opensearch-plugin install file:///opensearch/build/distributions/oci-repository-plugin-1.2.4.zip]: exit code: 1

### What is the expected behavior?
_A clear and concise description of what you expected to happen._
Plugin should install

### What is your host/environment?
_Operating system, version._

### Do you have any screenshots?
_If applicable, add screenshots to help explain your problem._

### Do you have any additional context?
_Add any other context about the problem._

**Comment by samuel-oci** [comment]
The issue seems to be that the descriptor file is packaged under `src/main/resources` in the zip file instead of the root, this should be a simple fix. Should be able to send it out shortly.

**Comment by samuel-oci** [comment]
@rakeshgl sent a PR out 
https://github.com/opensearch-project/opensearch-oci-object-storage/pull/11

**Comment by rakeshgl** [comment]
Getting this error with the changes - 

> [builder 20/20] RUN /usr/share/opensearch/bin/opensearch-plugin install file:///opensearch/build/distributions/oci-repository-plugin-1.2.4.zip:
#41 1.375 -> Installing file:///opensearch/build/distributions/oci-repository-plugin-1.2.4.zip
#41 1.376 -> Downloading file:///opensearch/build/distributions/oci-repository-plugin-1.2.4.zip
[=================================================] 100%?? 
#41 2.376 
#41 2.376 @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
#41 2.376 @     WARNING: plugin requires additional permissions     @
#41 2.376 @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
#41 2.376 * java.lang.RuntimePermission *
#41 2.376 * java.lang.RuntimePermission accessDeclaredMembers
#41 2.376 * java.lang.RuntimePermission getClassLoader
#41 2.376 * java.lang.RuntimePermission setFactory
#41 2.376 * java.lang.reflect.ReflectPermission suppressAccessChecks
#41 2.376 * java.net.SocketPermission * connect,listen,accept,resolve
#41 2.376 * java.util.PropertyPermission * read,write
#41 2.376 * java.util.PropertyPermission opensearch.allow_insecure_settings read,write
#41 2.376 * java.util.PropertyPermission sun.net.http.allowRestrictedHeaders write
#41 2.376 See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
#41 2.376 for descriptions of what these permissions allow and the associated risks.
#41 2.377 -> Failed installing file:///opensearch/build/distributions/oci-repository-plugin-1.2.4.zip
#41 2.377 -> Rolling back file:///opensearch/build/distributions/oci-repository-plugin-1.2.4.zip
#41 2.386 -> Rolled back file:///opensearch/build/distributions/oci-repository-plugin-1.2.4.zip
#41 2.386 Exception in thread "main" java.lang.IllegalStateException: unable to read from standard input; is standard input open and a tty attached?
#41 2.387 	at org.opensearch.cli.Terminal$SystemTerminal.readText(Terminal.java:286)
#41 2.387 	at org.opensearch.plugins.PluginSecurity.prompt(PluginSecurity.java:87)
#41 2.387 	at org.opensearch.plugins.PluginSecurity.confirmPolicyExceptions(PluginSecurity.java:80)
#41 2.387 	at org.opensearch.plugins.InstallPluginCommand.installPlugin(InstallPluginCommand.java:867)
#41 2.387 	at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:263)
#41 2.387 	at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:237)
#41 2.387 	at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:100)
#41 2.387 	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
#41 2.387 	at org.opensearch.cli.MultiCommand.execute(MultiCommand.java:104)
#41 2.388 	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
#41 2.388 	at org.opensearch.cli.Command.main(Command.java:101)
#41 2.388 	at org.opensearch.plugins.PluginCli.main(PluginCli.java:60)
------
executor failed running [/bin/sh -c /usr/share/opensearch/bin/opensearch-plugin install file:///opensearch/build/distributions/oci-repository-plugin-1.2.4.zip]: exit code: 1

**Comment by samuel-oci** [comment]
That's strange, it looks like you are running this from some kind of remote shell. I was able to confirm this works on local. Can you please try the same?

**Comment by rakeshgl** [comment]
[oci-repository-plugin-1.2.4.zip](https://github.com/opensearch-project/opensearch-oci-object-storage/files/8880561/oci-repository-plugin-1.2.4.zip)
I tried with local build as well, got the same error

**Comment by samuel-oci** [comment]
In your output it shows you are running it via docker:
```
[builder 20/20] RUN /usr/share/opensearch/bin/opensearch-plugin install file:///opensearch/build/distributions/oci-repository-plugin-1.2.4.zip
```
if you issue install command it would be expecting input of yes/no whether you accept permissions, and the error indicates that you are running it in a remote executor or docker or something that doesn't get any input.
To get this to work without waiting for cli input you would have to add the parameter `--batch` to your command like so:
`/usr/share/opensearch/bin/opensearch-plugin install --batch file:///opensearch/build/distributions/oci-repository-plugin-1.2.4.zip`

**Comment by rakeshgl** [comment]
thanks, it worked after adding the parameter --batch

**Comment by samuel-oci** [comment]
great! I merged the fix and closing the issue, thank you for reporting it.
