### ISSUE TITLE
[BUG] Add integration tests and CIs

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/opensearch-oci-object-storage#14]
### What is the bug?
This repo doesnt have any integration tests running for PRs and we do not know if a PR breaks the plugin.

**Comment by VachaShah** [comment]
@saratvemulapalli Looks like the CI `maven.yml` runs the tests in the repo.

**Comment by samuel-oci** [comment]
@saratvemulapalli can we close this one? As mentioned the tests are run by `maven.yml` and following https://github.com/opensearch-project/opensearch-oci-object-storage/pull/33 will also be run instead by `gradle.yml`
