### ISSUE TITLE
[FEATURE] Update the build system to gradle

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/opensearch-oci-object-storage#15]
### Is your feature request related to a problem?
OpenSearch recommends using gradle build system as it already exposes a lot of tools which can be used. 

### What is your proposal
Update the build system to gradle.

**Comment by samuel-oci** [comment]
Closing as this seems like a duplicate of https://github.com/opensearch-project/opensearch-oci-object-storage/issues/20
