### ISSUE TITLE
[FEATURE] Move the build system to Gradle

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/opensearch-oci-object-storage#20]
### Is your feature request related to a problem?
This plugin uses Maven to build, OpenSearch exports gradle plugins to help develop opensearch plugins easier. 

### What solution would you like?
Move away from Maven to Gradle

### What alternatives have you considered?
Not really!

**Comment by samuel-oci** [comment]
Hi @saratvemulapalli, I sent https://github.com/opensearch-project/opensearch-oci-object-storage/pull/33 to address this one. Would be great if you can review and/or add other reviewers to assist with review.
