### ISSUE TITLE
Baseline MAINTAINERS, CODEOWNERS, and external collaborator permissions

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-oci-object-storage#28]
Follow https://github.com/opensearch-project/.github/issues/125 to baseline MAINTAINERS, CODEOWNERS, and external collaborator permissions.

Close this issue when:

1. [MAINTAINERS.md](MAINTAINERS.md) has the correct list of project maintainers.
2. [CODEOWNERS](CODEOWNERS) exists and has the correct list of aliases.
3. Repo permissions only contain individual aliases as collaborators with maintain rights, admin, and triage teams. 
4. All other teams are removed from repo permissions.

If this repo's permissions was already baselined, please confirm the above when closing this issue.

**Comment by anasalkouz** [comment]
@ samuel-oci, could you please revoke admin access from clients group?

**Comment by samuel-oci** [comment]
Hi @anasalkouz , I don't think I have the capability to do so at the moment, perhaps I need to be able another permission to see all other admins?
<img width="1314" alt="image" src="https://user-images.githubusercontent.com/97131656/228931502-2596e4fe-6961-4423-838b-f40d04f3e016.png">

**Comment by anasalkouz** [comment]
@dblock Could you please help on this? neither I nor @samuel-oci  has access.

**Comment by dblock** [comment]
@bbarani I don't have access either, help?

**Comment by bbarani** [comment]
I am not seeing the setting tab to view the current list of maintainers as well. [samuel-oci](https://github.com/samuel-oci) can you try to add the team @opensearch-project/anomaly-detection arch-project/admin team?  I will reach out to the OpenSearch repository orgnaization owners if you are not able to do it.

**Comment by wbeckler** [comment]
@CEHENKLE @hyandell Can one of you change the @opensearch-project/admin team hear to Admin access rather than Read access, as appears in DB's screenshot above. I think this requires repo-level admin privileges as nobody has admin in this repo.

**Comment by hyandell** [comment]
@admin changed to have Admin perms.

**Comment by wbeckler** [comment]
I added the named maintainers as maintainers in the guithub permssions. @samuel-oci can you take a look and confirm the changes are okay?

**Comment by peternied** [comment]
Screenshot: ![image](https://user-images.githubusercontent.com/2754967/230680359-3e407213-a5f5-4a02-9321-53f8a8804c6d.png)

**Comment by samuel-oci** [comment]
Hi William,Unfortunately I have out of town with not much internet access until 04/17, can check when I’m back.Thanks,SamSent from my iPhoneOn Apr 7, 2023, at 6:51 PM, William Beckler ***@***.***> wrote:﻿
I added the named maintainers as maintainers in the guithub permssions. @samuel-oci can you take a look and confirm the changes are okay?

**Comment by anasalkouz** [comment]
@peternied changes looks good to me.

**Comment by anasalkouz** [comment]
I think we can resolve the issue now.
