### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by nknize** [opensearch-project/opensearch-oci-object-storage#53]
### What is the bug?
Build compatibility check fails with some javadoc issues. This was caught by the [compatibility checker](https://github.com/opensearch-project/OpenSearch/actions/runs/5742101583/job/15563536027?pr=9073#step:3:2678) on https://github.com/opensearch-project/OpenSearch/pull/9073.

### How can one reproduce the bug?
Build with latest version of core SNAPSHOT

### What is the expected behavior?
No javadoc failures

### Do you have any screenshots?
```
/tmp/groovy-generated-tmpdir-4704034333506418947/plugin/build/generated/sources/delombok/java/main/org/opensearch/ml/breaker/MLCircuitBreakerService.java:66: warning: no description for @param
     * @param path
       ^
/tmp/groovy-generated-tmpdir-4704034333506418947/plugin/build/generated/sources/delombok/java/main/org/opensearch/ml/model/MLModelCache.java:66: warning: no description for @param
     * @param nodeId
       ^
/tmp/groovy-generated-tmpdir-4704034333506418947/plugin/build/generated/sources/delombok/java/main/org/opensearch/ml/model/MLModelCache.java:67: warning: no description for @param
     * @param isFromUndeploy
       ^
/tmp/groovy-generated-tmpdir-4704034333506418947/plugin/build/generated/sources/delombok/java/main/org/opensearch/ml/model/MLModelCache.java:90: warning: no description for @param
     * @param nodeId  
```

### Do you have any additional context?
[#5910](https://github.com/opensearch-project/OpenSearch/issues/5910)

**Comment by gaiksaya** [comment]
Issue with console logs. OCI Object storage plugin is good as per the final result:

Incompatible components: [https://github.com/opensearch-project/index-management.git, https://github.com/opensearch-project/anomaly-detection.git, https://github.com/opensearch-project/asynchronous-search.git, https://github.com/opensearch-project/geospatial.git, https://github.com/opensearch-project/performance-analyzer.git, https://github.com/opensearch-project/security-analytics.git]
