### ISSUE TITLE
[BUG] docker build fails with java.lang.NoClassDefFoundError: Could not initialize class org.opensearch.test.OpenSearchTestCase

### ISSUE THREAD

**Issue by rakeshgl** [opensearch-project/opensearch-oci-object-storage#9]
### What is the bug?
failure in running mvn clean install in docker env

### How can one reproduce the bug?
_Steps to reproduce the behavior._
Here is the excerpt of the dockerfile. Run docker build with this dockerfile to reproduce -
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
RUN yum install -y git && \
    yum install maven 

RUN git clone https://github.com/opensearch-project/opensearch-oci-object-storage.git .

RUN mvn clean install -X -e -PAdvanced
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

### What is the expected behavior?
Successful build

### What is your host/environment?
docker build

### Do you have any screenshots?
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#13 267.2 SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
#13 267.2 SLF4J: Defaulting to no-operation (NOP) logger implementation
#13 267.2 SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
#13 430.9 Exception in thread "Thread-1" java.lang.NoClassDefFoundError: Could not initialize class org.opensearch.test.OpenSearchTestCase
#13 430.9 	at java.base/java.lang.Thread.run(Thread.java:834)
#13 430.9 	Suppressed: java.lang.IllegalStateException: No context information for thread: Thread[id=15, name=Thread-1, state=RUNNABLE, group=TGRP-OciObjectStoragePluginTest]. Is this thread running under a class com.carrotsearch.randomizedtesting.RandomizedRunner runner context? Add @RunWith(class com.carrotsearch.randomizedtesting.RandomizedRunner.class) to your test class. Make sure your code accesses random contexts within @BeforeClass and @AfterClass boundary (for example, static test class initializers are not permitted to access random contexts).
#13 430.9 		at com.carrotsearch.randomizedtesting.RandomizedContext.context(RandomizedContext.java:249)
#13 430.9 		at com.carrotsearch.randomizedtesting.RandomizedContext.current(RandomizedContext.java:134)
#13 430.9 		at com.carrotsearch.randomizedtesting.RandomizedRunner.augmentStackTrace(RandomizedRunner.java:1885)
#13 430.9 		at com.carrotsearch.randomizedtesting.RunnerThreadGroup.uncaughtException(RunnerThreadGroup.java:20)
#13 430.9 		at java.base/java.lang.Thread.dispatchUncaughtException(Thread.java:2001)

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

### Do you have any additional context?
_Add any other context about the problem._

**Comment by samuel-oci** [comment]
@rakeshgl is the issue specific to your docker environment? are you able to build the project in a non-docker?

**Comment by samuel-oci** [comment]
@rakeshgl any update on this? we do see the build is working in the pipeline job and also working locally, can you share your docker environment setup? also have you seen this failing outside of docker or just within your docker environment?

**Comment by rakeshgl** [comment]
@samuel-oci this occurs only within the docker environment.

**Comment by rakeshgl** [comment]
This is from my Dockerfile -

**Comment by samuel-oci** [comment]
@rakeshgl I don't think we can consider this as bug but rather a question, and that is for the following reasons:
1. The build and test workflows show there is no issue with building the plugin
2. Upon looking at the The issue you are describing, this is very specific to your individual local setup of build from docker which is not currently supported

I think the best path here would be for us to do best effort to help answer your question and later close the issue. Just want to make sure we set the right expectation before proceeding.

It seems like you were trying to paste your dockerfile earlier but it got truncated.
